Festo: Dispatcher Class Reference
Dispatcher Class Reference
#include <Dispatcher.h>
Public Member Functions
virtual ~Dispatcher ()
int getChannelId ()
used to get Channel ID from outside this class
virtual void execute (void *arg)
virtual void shutdown ()
Public Member Functions inherited from thread::HAWThread
HAWThread ()
virtual ~HAWThread ()
void start (void *arg)
void stop ()
void join () const
void hold ()
void cont ()
Static Public Member Functions
static Dispatcher * getInstance ()
For Singleton pattern implementation.
Private Member Functions
Dispatcher ()
Private Attributes
int channel_id_
Dispatcher's channel ID.
int con_id_
Connection ID to own channel.
Demultiplexer * demultiplexer_
Static Private Attributes
static Dispatcher * dispatcher_instance_ = NULL
The only dispatcher's instance.
static Mutex dispatcher_mutex_ = Mutex()
Mutex used in Singleton implementation.
Additional Inherited Members
Protected Member Functions inherited from thread::HAWThread
void run (void *arg)
void * Arg () const
void Arg (void *a)
bool isStopped () const
void shutdownAll ()
Static Protected Member Functions inherited from thread::HAWThread
static void * entryPoint (void *)
Detailed Description
Definition at line 30 of file Dispatcher.h.
Constructor & Destructor Documentation
Dispatcher::~Dispatcher () virtual
free memory used by dispatcher's instance detach from the channel and destroy it
Definition at line 33 of file Dispatcher.cpp.
References channel_id_, con_id_, and dispatcher_instance_.
Dispatcher::Dispatcher () private
Create a channel and attach to it to get messages from Demultiplexer and controller (for errors i.e)
Definition at line 25 of file Dispatcher.cpp.
References demultiplexer_, and Demultiplexer::getInstance().
Referenced by getInstance().
Member Function Documentation
void Dispatcher::execute (void * arg) virtual
All the Dispatcher's work will be done here It gets messages from its channel and make call-backs using its event handker table
Implements thread::HAWThread.
Definition at line 73 of file Dispatcher.cpp.
References con_id_, CONTROLLER_CODE, demultiplexer_, DEMULTIPLEXER_CODE, E_STOP_PRESSED, E_STOP_RELEASED, Demultiplexer::getChannelId(), thread::HAWThread::isStopped(), RESET_PRESSED, RESET_RELEASED, SLIDE_FULL, thread::HAWThread::start(), START_PRESSED, START_RELEASED, STOP_PRESSED, STOP_RELEASED, WP_IN_ENGINE_END, WP_IN_ENGINE_START, WP_IN_HEIGHT_M, WP_IN_SLIDE, WP_IN_SWITCH, WP_IN_TOLERANCE_R, WP_IS_METAL, WP_IS_MISSING, WP_IS_STRANGER, WP_NOT_IN_TOLERANCE_R, WP_NOT_METAL, WP_NOT_TURNED, WP_OUT_ENGINE_END, WP_OUT_ENGINE_START, WP_OUT_HEIGHT_M, WP_OUT_SLIDE, and WP_OUT_SWITCH.
int Dispatcher::getChannelId ()
used to get Channel ID from outside this class
Returns
Dispatcher's channel ID
Return channel id. It will be used from outside to connect to dispatcher's channel
Definition at line 65 of file Dispatcher.cpp.
References channel_id_.
Dispatcher * Dispatcher::getInstance () static
For Singleton pattern implementation.
Returns
Dispatcher's instance
return an Instance of the Dispatcher At most one instance of Dispatcher will be created. If no instance has been created yet, a new instance has to be created. Otherwise the already created instance will be returned.
Definition at line 47 of file Dispatcher.cpp.
References Dispatcher(), dispatcher_instance_, dispatcher_mutex_, Mutex::lock(), and Mutex::unlock().
Referenced by main().
void Dispatcher::shutdown () virtual
this function must be implemented in the derived class. The function is called once after the thread has been stopped.
Implements thread::HAWThread.
Definition at line 188 of file Dispatcher.cpp.
Member Data Documentation
int Dispatcher::channel_id_ private
Dispatcher's channel ID.
Definition at line 48 of file Dispatcher.h.
Referenced by getChannelId(), and ~Dispatcher().
int Dispatcher::con_id_ private
Connection ID to own channel.
Definition at line 49 of file Dispatcher.h.
Referenced by execute(), and ~Dispatcher().
Demultiplexer* Dispatcher::demultiplexer_ private
Definition at line 53 of file Dispatcher.h.
Referenced by Dispatcher(), and execute().
Dispatcher * Dispatcher::dispatcher_instance_ = NULL static private
The only dispatcher's instance.
Definition at line 50 of file Dispatcher.h.
Referenced by getInstance(), and ~Dispatcher().
Mutex Dispatcher::dispatcher_mutex_ = Mutex() static private
Mutex used in Singleton implementation.
Definition at line 51 of file Dispatcher.h.
Referenced by getInstance().
The documentation for this class was generated from the following files:
Dispatcher/Dispatcher.h
Dispatcher/Dispatcher.cpp