Festo: Mutex Class Reference
Mutex Class Reference
#include <Mutex.h>
Public Member Functions
Mutex ()
virtual ~Mutex ()
void lock ()
void unlock ()
Private Attributes
pthread_mutex_t mutex_
Detailed Description
Definition at line 14 of file Mutex.h.
Constructor & Destructor Documentation
Mutex::Mutex ()
Initialize the Mutex
Definition at line 15 of file Mutex.cpp.
References mutex_.
Mutex::~Mutex () virtual
Destroy the Mutex
Definition at line 22 of file Mutex.cpp.
References mutex_.
Member Function Documentation
void Mutex::lock ()
Unlock the Mutex
Definition at line 38 of file Mutex.cpp.
References mutex_.
Referenced by HALSensoric::getInstance(), Demultiplexer::getInstance(), Dispatcher::getInstance(), PortC::set_Bit_off(), PortA::set_Bit_off(), PortC::set_Bit_on(), and PortA::set_Bit_on().
void Mutex::unlock ()
Lock the Mutex
Definition at line 30 of file Mutex.cpp.
References mutex_.
Referenced by HALSensoric::getInstance(), Demultiplexer::getInstance(), Dispatcher::getInstance(), PortC::set_Bit_off(), PortA::set_Bit_off(), PortC::set_Bit_on(), and PortA::set_Bit_on().
Member Data Documentation
pthread_mutex_t Mutex::mutex_ private
Definition at line 22 of file Mutex.h.
Referenced by lock(), Mutex(), unlock(), and ~Mutex().
The documentation for this class was generated from the following files:
Mutex/Mutex.h
Mutex/Mutex.cpp