Festo: LightTest Class Reference
LightTest Class Reference
#include <LightTest.h>
Public Member Functions
LightTest ()
virtual ~LightTest ()
Public Member Functions inherited from thread::HAWThread
HAWThread ()
virtual ~HAWThread ()
void start (void *arg)
void stop ()
void join () const
void hold ()
void cont ()
Private Member Functions
virtual void execute (void *arg)
virtual void shutdown ()
Additional Inherited Members
Protected Member Functions inherited from thread::HAWThread
void run (void *arg)
void * Arg () const
void Arg (void *a)
bool isStopped () const
void shutdownAll ()
Static Protected Member Functions inherited from thread::HAWThread
static void * entryPoint (void *)
Detailed Description
Definition at line 14 of file LightTest.h.
Constructor & Destructor Documentation
LightTest::LightTest ()
Definition at line 13 of file LightTest.cpp.
LightTest::~LightTest () virtual
Definition at line 18 of file LightTest.cpp.
Member Function Documentation
void LightTest::execute (void *) private virtual
   * (loop)
to be implemented in the derived class. The application programmer has to write his own loop. He can check bool isStopped() to see if the thread should exit the loop.
Implements thread::HAWThread.
Definition at line 22 of file LightTest.cpp.
References HALAktorik::getInstance(), HALAktorik::green_Light_off(), HALAktorik::green_Light_on(), HALAktorik::red_Light_off(), HALAktorik::red_Light_on(), HALAktorik::red_Light_quick(), HALAktorik::red_Light_slow(), WAIT_THREE_S, HALAktorik::yellow_Light_off(), and HALAktorik::yellow_Light_on().
void LightTest::shutdown () private virtual
this function must be implemented in the derived class. The function is called once after the thread has been stopped.
Implements thread::HAWThread.
Definition at line 60 of file LightTest.cpp.
The documentation for this class was generated from the following files:
Tests/LightTest.h
Tests/LightTest.cpp