Festo: MotorTest Class Reference
MotorTest Class Reference
#include <MotorTest.h>
Public Member Functions
MotorTest ()
virtual ~MotorTest ()
Public Member Functions inherited from thread::HAWThread
HAWThread ()
virtual ~HAWThread ()
void start (void *arg)
void stop ()
void join () const
void hold ()
void cont ()
Private Member Functions
virtual void execute (void *arg)
virtual void shutdown ()
Additional Inherited Members
Protected Member Functions inherited from thread::HAWThread
void run (void *arg)
void * Arg () const
void Arg (void *a)
bool isStopped () const
void shutdownAll ()
Static Protected Member Functions inherited from thread::HAWThread
static void * entryPoint (void *)
Detailed Description
Definition at line 13 of file MotorTest.h.
Constructor & Destructor Documentation
MotorTest::MotorTest ()
Definition at line 13 of file MotorTest.cpp.
MotorTest::~MotorTest () virtual
Definition at line 18 of file MotorTest.cpp.
Member Function Documentation
void MotorTest::execute (void *) private virtual
   * (loop)
to be implemented in the derived class. The application programmer has to write his own loop. He can check bool isStopped() to see if the thread should exit the loop.
Implements thread::HAWThread.
Definition at line 22 of file MotorTest.cpp.
References HALAktorik::getInstance(), HALAktorik::motor_off(), HALAktorik::motor_on(), and WAIT_TEN_S.
void MotorTest::shutdown () private virtual
this function must be implemented in the derived class. The function is called once after the thread has been stopped.
Implements thread::HAWThread.
Definition at line 32 of file MotorTest.cpp.
The documentation for this class was generated from the following files:
Tests/MotorTest.h
Tests/MotorTest.cpp