Festo: PortA Class Reference
PortA Class Reference
#include <PortA.h>
Public Member Functions
PortA ()
Constructor.
virtual ~PortA ()
Destructor.
void set_Bit_on (uint8_t bitNumber)
Set a bit on.
void set_Bit_off (uint8_t bitNumber)
Set a bit off.
void green_Light_on ()
Turn green light on.
void green_Light_off ()
Turn green light off.
void yellow_Light_on ()
Turn yellow light on.
void yellow_Light_off ()
Turn yellow light off.
void red_Light_on ()
Turn red light on.
void red_Light_off ()
Turn red light off.
void red_Light_slow ()
Start red light flashing slowly.
void red_Light_quick ()
Start red light flashing quickly.
void motor_on ()
Turn motor on.
void motor_off ()
Turn motor off.
void run_slow ()
Run production line slowly.
void run_right ()
Run production line from right to left.
void run_left ()
Run production line from left to right.
void stop_Motor ()
Stop motor.
void open_Switch ()
Open the switch.
void close_Switch ()
Close the switch.
bool is_Switch_Open ()
Return the switch's state.
Static Private Attributes
static Mutex * portA_mutex_ = new Mutex()
Mutex for thread-safe implementation.
Detailed Description
Definition at line 19 of file PortA.h.
Constructor & Destructor Documentation
PortA::PortA ()
Constructor.
Constructor does nothing
Definition at line 26 of file PortA.cpp.
PortA::~PortA () virtual
Destructor.
Destructor does nothing
Definition at line 32 of file PortA.cpp.
Member Function Documentation
void PortA::close_Switch ()
Close the switch.
See Also
set_Bit_off()
Definition at line 209 of file PortA.cpp.
References BIT_4, and set_Bit_off().
void PortA::green_Light_off ()
Turn green light off.
See Also
set_Bit_off()
Definition at line 131 of file PortA.cpp.
References BIT_5, and set_Bit_off().
void PortA::green_Light_on ()
Turn green light on.
See Also
set_Bit_on()
Definition at line 124 of file PortA.cpp.
References BIT_5, and set_Bit_on().
bool PortA::is_Switch_Open ()
Return the switch's state.
Returns
true if the switch is open
Definition at line 195 of file PortA.cpp.
References BIT_4, and DIGITAL_CARD_CROUP0_PORTA.
void PortA::motor_off ()
Turn motor off.
See Also
set_Bit_off()
Definition at line 84 of file PortA.cpp.
References BIT_0, and set_Bit_off().
void PortA::motor_on ()
Turn motor on.
See Also
set_Bit_on()
Definition at line 77 of file PortA.cpp.
References BIT_0, and set_Bit_on().
void PortA::open_Switch ()
Open the switch.
See Also
set_Bit_on()
Definition at line 202 of file PortA.cpp.
References BIT_4, and set_Bit_on().
void PortA::red_Light_off ()
Turn red light off.
See Also
set_Bit_off()
Definition at line 159 of file PortA.cpp.
References BIT_7, and set_Bit_off().
Referenced by red_Light_quick(), and red_Light_slow().
void PortA::red_Light_on ()
Turn red light on.
See Also
set_Bit_on()
Definition at line 152 of file PortA.cpp.
References BIT_7, and set_Bit_on().
Referenced by red_Light_quick(), and red_Light_slow().
void PortA::red_Light_quick ()
Start red light flashing quickly.
Definition at line 177 of file PortA.cpp.
References red_Light_off(), red_Light_on(), and WAIT_HALF_S.
void PortA::red_Light_slow ()
Start red light flashing slowly.
Definition at line 164 of file PortA.cpp.
References red_Light_off(), red_Light_on(), and WAIT_ONE_S.
void PortA::run_left ()
Run production line from left to right.
See Also
set_Bit_on()
Definition at line 98 of file PortA.cpp.
References BIT_1, and set_Bit_on().
void PortA::run_right ()
Run production line from right to left.
See Also
set_Bit_on()
Definition at line 91 of file PortA.cpp.
References BIT_0, and set_Bit_on().
void PortA::run_slow ()
Run production line slowly.
See Also
set_Bit_on()
Definition at line 105 of file PortA.cpp.
References BIT_2, and set_Bit_on().
void PortA::set_Bit_off (uint8_t bitNumber)
Set a bit off.
Parameters
bitNumber Bit's mask to set off
This method takes the bit's mask which has to be set off as parameter and it's thread-safe.
See Also
portA_mutex
Definition at line 56 of file PortA.cpp.
References DIGITAL_CARD_CROUP0_PORTA, Mutex::lock(), portA_mutex_, and Mutex::unlock().
Referenced by close_Switch(), green_Light_off(), motor_off(), red_Light_off(), and yellow_Light_off().
void PortA::set_Bit_on (uint8_t bitNumber)
Set a bit on.
Parameters
bitNumber Bit's mask to set on
This method takes the bit's mask which has to be set on as parameter and it's thread-safe.
See Also
portA_mutex
Definition at line 39 of file PortA.cpp.
References DIGITAL_CARD_CROUP0_PORTA, Mutex::lock(), portA_mutex_, and Mutex::unlock().
Referenced by green_Light_on(), motor_on(), open_Switch(), red_Light_on(), run_left(), run_right(), run_slow(), stop_Motor(), and yellow_Light_on().
void PortA::stop_Motor ()
Stop motor.
See Also
set_Bit_on()
Definition at line 112 of file PortA.cpp.
References BIT_3, and set_Bit_on().
void PortA::yellow_Light_off ()
Turn yellow light off.
See Also
set_Bit_off()
Definition at line 145 of file PortA.cpp.
References BIT_6, and set_Bit_off().
void PortA::yellow_Light_on ()
Turn yellow light on.
See Also
set_Bit_on()
Definition at line 138 of file PortA.cpp.
References BIT_6, and set_Bit_on().
Member Data Documentation
Mutex * PortA::portA_mutex_ = new Mutex() static private
Mutex for thread-safe implementation.
It locks and unlocks access to Port A to assure thread-safe implementation.
See Also
set_Bit_on()
set_Bit_off()
Definition at line 57 of file PortA.h.
Referenced by set_Bit_off(), and set_Bit_on().
The documentation for this class was generated from the following files:
HAL/PortA.h
HAL/PortA.cpp