Festo: thread::MyThread Class Reference
thread::MyThread Class Reference
#include <MyThread.h>
Public Member Functions
MyThread ()
virtual ~MyThread ()
virtual void execute (void *arg)
virtual void shutdown ()
Public Member Functions inherited from thread::HAWThread
HAWThread ()
virtual ~HAWThread ()
void start (void *arg)
void stop ()
void join () const
void hold ()
void cont ()
Additional Inherited Members
Protected Member Functions inherited from thread::HAWThread
void run (void *arg)
void * Arg () const
void Arg (void *a)
bool isStopped () const
void shutdownAll ()
Static Protected Member Functions inherited from thread::HAWThread
static void * entryPoint (void *)
Detailed Description
Definition at line 18 of file MyThread.h.
Constructor & Destructor Documentation
MyThread::MyThread ()
Definition at line 22 of file MyThread.cpp.
MyThread::~MyThread () virtual
Definition at line 26 of file MyThread.cpp.
Member Function Documentation
void MyThread::execute (void *) virtual
   * (loop)
to be implemented in the derived class. The application programmer has to write his own loop. He can check bool isStopped() to see if the thread should exit the loop.
Implements thread::HAWThread.
Definition at line 34 of file MyThread.cpp.
References HALAktorik::close_Switch(), HALAktorik::getInstance(), HALAktorik::green_Light_off(), HALAktorik::green_Light_on(), thread::HAWThread::isStopped(), HALAktorik::motor_off(), HALAktorik::motor_on(), HALAktorik::open_Switch(), HALAktorik::red_Light_off(), HALAktorik::red_Light_on(), HALAktorik::yellow_Light_off(), and HALAktorik::yellow_Light_on().
void MyThread::shutdown () virtual
this function must be implemented in the derived class. The function is called once after the thread has been stopped.
Implements thread::HAWThread.
Definition at line 30 of file MyThread.cpp.
The documentation for this class was generated from the following files:
Controler/MyThread.h
Controler/MyThread.cpp