Festo: HALAktorik Class Reference
HALAktorik Class Reference
#include <HALAktorik.h>
Public Member Functions
virtual ~HALAktorik ()
Destructor.
void green_Light_on ()
Turn green light on.
void green_Light_off ()
Turn green light off.
void yellow_Light_on ()
Turn yellow light on.
void yellow_Light_off ()
Turn yellow light off.
void red_Light_on ()
Turn red light on.
void red_Light_off ()
Turn red light off.
void red_Light_slow ()
Start red light flashing slowly.
void red_Light_quick ()
Start red light flashing quickly.
void motor_on ()
Turn motor on.
void motor_off ()
Turn motor off.
void run_slow ()
Run production line slowly.
void run_right ()
Run production line from right to left.
void run_left ()
Run production line from left to right.
void stop_Motor ()
Stop motor.
void open_Switch ()
Open the switch.
void close_Switch ()
Close the switch.
bool is_Switch_Open ()
Return the switch's state.
void Start_LED_on ()
Turn Start-LED on.
void Start_LED_off ()
Turn Start-LED off.
void Reset_LED_on ()
Turn Reset-LED on.
void Reset_LED_off ()
Turn Reset-LED off.
void Q1_LED_on ()
Turn Q1-LED on.
void Q1_LED_off ()
Turn Q1-LED off.
void Q2_LED_on ()
Turn Q2-LED on.
void Q2_LED_off ()
Turn Q2-LED off.
Static Public Member Functions
static HALAktorik * getInstance ()
Used to implement Singleton Pattern.
Private Member Functions
HALAktorik ()
Constructor has to be private for the singleton pattern implementation.
Private Attributes
PortA * portA_
Represent Port A.
PortC * portC_
Represent Port C.
Static Private Attributes
static HALAktorik * hal_Aktorik_instance_ = NULL
The only instance of HAL.
static Mutex * hal_Aktorik_mutex_ = new Mutex()
Mutex for thread-safe implementation.
Detailed Description
Definition at line 20 of file HALAktorik.h.
Constructor & Destructor Documentation
HALAktorik::~HALAktorik () virtual
Destructor.
Free memory allocated by HAL.
See Also
HALAktorik()
Definition at line 36 of file HALAktorik.cpp.
HALAktorik::HALAktorik () private
Constructor has to be private for the singleton pattern implementation.
Test access' right and initialize IO-card in case of success.
Definition at line 21 of file HALAktorik.cpp.
References DIGITAL_CARD_CONTROL.
Member Function Documentation
void HALAktorik::close_Switch ()
Close the switch.
Definition at line 101 of file HALAktorik.cpp.
Referenced by SwitchTest::execute(), and thread::MyThread::execute().
HALAktorik * HALAktorik::getInstance () static
Used to implement Singleton Pattern.
Returns
instance of HALAktorik
At most one instance of HALAktorik will be created. If no instance has been created yet, a new instance has to be created. Otherwise the already created instance will be returned.
Definition at line 47 of file HALAktorik.cpp.
Referenced by LEDTest::execute(), MotorTest::execute(), SwitchTest::execute(), LightTest::execute(), and thread::MyThread::execute().
void HALAktorik::green_Light_off ()
Turn green light off.
Definition at line 119 of file HALAktorik.cpp.
Referenced by LightTest::execute(), and thread::MyThread::execute().
void HALAktorik::green_Light_on ()
Turn green light on.
Definition at line 115 of file HALAktorik.cpp.
Referenced by LightTest::execute(), and thread::MyThread::execute().
bool HALAktorik::is_Switch_Open ()
Return the switch's state.
Returns
true if the switch is open
Definition at line 105 of file HALAktorik.cpp.
void HALAktorik::motor_off ()
Turn motor off.
Definition at line 67 of file HALAktorik.cpp.
Referenced by MotorTest::execute(), and thread::MyThread::execute().
void HALAktorik::motor_on ()
Turn motor on.
Definition at line 63 of file HALAktorik.cpp.
Referenced by MotorTest::execute(), and thread::MyThread::execute().
void HALAktorik::open_Switch ()
Open the switch.
Definition at line 97 of file HALAktorik.cpp.
Referenced by SwitchTest::execute(), and thread::MyThread::execute().
void HALAktorik::Q1_LED_off ()
Turn Q1-LED off.
Definition at line 157 of file HALAktorik.cpp.
Referenced by LEDTest::execute().
void HALAktorik::Q1_LED_on ()
Turn Q1-LED on.
Definition at line 153 of file HALAktorik.cpp.
Referenced by LEDTest::execute().
void HALAktorik::Q2_LED_off ()
Turn Q2-LED off.
Definition at line 165 of file HALAktorik.cpp.
Referenced by LEDTest::execute().
void HALAktorik::Q2_LED_on ()
Turn Q2-LED on.
Definition at line 161 of file HALAktorik.cpp.
Referenced by LEDTest::execute().
void HALAktorik::red_Light_off ()
Turn red light off.
Definition at line 127 of file HALAktorik.cpp.
Referenced by LightTest::execute(), and thread::MyThread::execute().
void HALAktorik::red_Light_on ()
Turn red light on.
Definition at line 123 of file HALAktorik.cpp.
Referenced by LightTest::execute(), and thread::MyThread::execute().
void HALAktorik::red_Light_quick ()
Start red light flashing quickly.
Definition at line 143 of file HALAktorik.cpp.
Referenced by LightTest::execute().
void HALAktorik::red_Light_slow ()
Start red light flashing slowly.
Definition at line 139 of file HALAktorik.cpp.
Referenced by LightTest::execute().
void HALAktorik::Reset_LED_off ()
Turn Reset-LED off.
Definition at line 181 of file HALAktorik.cpp.
Referenced by LEDTest::execute().
void HALAktorik::Reset_LED_on ()
Turn Reset-LED on.
Definition at line 177 of file HALAktorik.cpp.
Referenced by LEDTest::execute().
void HALAktorik::run_left ()
Run production line from left to right.
Definition at line 83 of file HALAktorik.cpp.
void HALAktorik::run_right ()
Run production line from right to left.
Definition at line 79 of file HALAktorik.cpp.
void HALAktorik::run_slow ()
Run production line slowly.
Definition at line 87 of file HALAktorik.cpp.
void HALAktorik::Start_LED_off ()
Turn Start-LED off.
Definition at line 173 of file HALAktorik.cpp.
Referenced by LEDTest::execute().
void HALAktorik::Start_LED_on ()
Turn Start-LED on.
Definition at line 169 of file HALAktorik.cpp.
Referenced by LEDTest::execute().
void HALAktorik::stop_Motor ()
Stop motor.
Motor could be stopped by changing BIT_3, not changing BIT_1, BIT_2 or BIT_3 could be used to hold the band for a defined time too.
Definition at line 75 of file HALAktorik.cpp.
void HALAktorik::yellow_Light_off ()
Turn yellow light off.
Definition at line 135 of file HALAktorik.cpp.
Referenced by LightTest::execute(), and thread::MyThread::execute().
void HALAktorik::yellow_Light_on ()
Turn yellow light on.
Definition at line 131 of file HALAktorik.cpp.
Referenced by LightTest::execute(), and thread::MyThread::execute().
Member Data Documentation
HALAktorik * HALAktorik::hal_Aktorik_instance_ = NULL static private
The only instance of HAL.
Definition at line 65 of file HALAktorik.h.
Mutex * HALAktorik::hal_Aktorik_mutex_ = new Mutex() static private
Mutex for thread-safe implementation.
Definition at line 66 of file HALAktorik.h.
PortA* HALAktorik::portA_ private
Represent Port A.
Definition at line 63 of file HALAktorik.h.
PortC* HALAktorik::portC_ private
Represent Port C.
Definition at line 64 of file HALAktorik.h.
The documentation for this class was generated from the following files:
HAL/HALAktorik.h
HAL/HALAktorik.cpp