Festo: Demultiplexer Class Reference
Demultiplexer Class Reference
#include <Demultiplexer.h>
Public Member Functions
virtual ~Demultiplexer ()
int getChannelId ()
used to get Channel ID from outside this class
virtual void execute (void *arg)
virtual void shutdown ()
Public Member Functions inherited from thread::HAWThread
HAWThread ()
virtual ~HAWThread ()
void start (void *arg)
void stop ()
void join () const
void hold ()
void cont ()
Static Public Member Functions
static Demultiplexer * getInstance ()
For Singleton pattern implementation.
Private Member Functions
Demultiplexer ()
void init ()
Init dispatcher and HALSensoric.
int sendMsg2D (int message)
Send message to Dispatcher.
Private Attributes
int channel_id_
get Channel ID to receive and send messages
int con_id_
Connection ID : with HAL Sensoric.
HALSensoric * hal_sensoric_
Static Private Attributes
static Demultiplexer * demultiplexer_instance_ = NULL
The only demultiplexer's instance.
static Mutex demultiplexer_mutex_ = Mutex()
Mutex used in Singleton implementation.
Additional Inherited Members
Protected Member Functions inherited from thread::HAWThread
void run (void *arg)
void * Arg () const
void Arg (void *a)
bool isStopped () const
void shutdownAll ()
Static Protected Member Functions inherited from thread::HAWThread
static void * entryPoint (void *)
Detailed Description
Definition at line 25 of file Demultiplexer.h.
Constructor & Destructor Documentation
Demultiplexer::~Demultiplexer () virtual
free memory reserved by demultiplexer's instance
Definition at line 32 of file Demultiplexer.cpp.
References con_id_, and demultiplexer_instance_.
Demultiplexer::Demultiplexer () private
get HALSensoric's and dispatcher's instances
Definition at line 24 of file Demultiplexer.cpp.
References init().
Referenced by getInstance().
Member Function Documentation
void Demultiplexer::execute (void * arg) virtual
Here is where all the demultiplexer's work will be done It gets pulses from Halsensoric, interprets them and send the appropriate message to Dispatcher
Implements thread::HAWThread.
Definition at line 96 of file Demultiplexer.cpp.
References DIGITAL_CARD_CROUP0_PORTB, DIGITAL_CARD_CROUP0_PORTC, E_STOP_BUTTON, E_STOP_RELEASED, ENGINE_END, ENGINE_START, HALSensoric::getChannelId(), hal_sensoric_, HEIGHT_SENSOR, HEIGHT_STATUS, thread::HAWThread::isStopped(), METAL_STATUS, RESET_BUTTON, RESET_PRESSED, RESET_RELEASED, sendMsg2D(), SLIDE_STATUS, START_BUTTON, START_PRESSED, START_RELEASED, STOP_BUTTON, STOP_PRESSED, STOP_RELEASED, SWITCH_IS_CLOSED, SWITCH_IS_OPEN, SWITCH_STATUS, WP_IN_ENGINE_END, WP_IN_ENGINE_START, WP_IN_HEIGHT_M, WP_IN_SLIDE, WP_IN_SWITCH, WP_IN_TOLERANCE_R, WP_IS_IN_SWITCH, WP_IS_METAL, WP_NOT_IN_TOLERANCE_R, WP_NOT_METAL, WP_OUT_ENGINE_END, WP_OUT_ENGINE_START, WP_OUT_HEIGHT_M, WP_OUT_SLIDE, and WP_OUT_SWITCH.
int Demultiplexer::getChannelId ()
used to get Channel ID from outside this class
Returns
Demultiplexer's channel ID
Definition at line 87 of file Demultiplexer.cpp.
References channel_id_.
Referenced by Dispatcher::execute().
Demultiplexer * Demultiplexer::getInstance () static
For Singleton pattern implementation.
Returns
Demupltiplexer's instance
return an Instance of the Demultiplexer At most one instance of Demultiplexer will be created. If no instance has been created yet, a new instance has to be created. Otherwise the already created instance will be returned.
Definition at line 47 of file Demultiplexer.cpp.
References Demultiplexer(), demultiplexer_instance_, demultiplexer_mutex_, Mutex::lock(), and Mutex::unlock().
Referenced by Dispatcher::Dispatcher().
void Demultiplexer::init () private
Init dispatcher and HALSensoric.
Do some initialization work : Get HALSensoric instance Create a channel and attach to it
Definition at line 67 of file Demultiplexer.cpp.
References channel_id_, con_id_, HALSensoric::getInstance(), and hal_sensoric_.
Referenced by Demultiplexer().
int Demultiplexer::sendMsg2D (int message) private
Send message to Dispatcher.
Parameters
message Message to be sent to Dispatcher
Returns
0 in case of success, otherwise -1
Send a message to Dispatcher
Definition at line 281 of file Demultiplexer.cpp.
References con_id_, DEMULTIPLEXER_CODE, and thread::HAWThread::isStopped().
Referenced by execute().
void Demultiplexer::shutdown () virtual
this function must be implemented in the derived class. The function is called once after the thread has been stopped.
Implements thread::HAWThread.
Definition at line 302 of file Demultiplexer.cpp.
Member Data Documentation
int Demultiplexer::channel_id_ private
get Channel ID to receive and send messages
Definition at line 50 of file Demultiplexer.h.
Referenced by getChannelId(), and init().
int Demultiplexer::con_id_ private
Connection ID : with HAL Sensoric.
Definition at line 51 of file Demultiplexer.h.
Referenced by init(), sendMsg2D(), and ~Demultiplexer().
Demultiplexer * Demultiplexer::demultiplexer_instance_ = NULL static private
The only demultiplexer's instance.
Definition at line 53 of file Demultiplexer.h.
Referenced by getInstance(), and ~Demultiplexer().
Mutex Demultiplexer::demultiplexer_mutex_ = Mutex() static private
Mutex used in Singleton implementation.
Definition at line 54 of file Demultiplexer.h.
Referenced by getInstance().
HALSensoric* Demultiplexer::hal_sensoric_ private
Definition at line 52 of file Demultiplexer.h.
Referenced by execute(), and init().
The documentation for this class was generated from the following files:
Dispatcher/Demultiplexer.h
Dispatcher/Demultiplexer.cpp