Festo: SensoricTest Class Reference
SensoricTest Class Reference
#include <SensoricTest.h>
Public Member Functions
SensoricTest ()
virtual ~SensoricTest ()
virtual void execute (void *arg)
virtual void shutdown ()
Public Member Functions inherited from thread::HAWThread
HAWThread ()
virtual ~HAWThread ()
void start (void *arg)
void stop ()
void join () const
void hold ()
void cont ()
Private Attributes
HALAktorik * hal_aktorik_
HAL Aktorik instance.
HALSensoric * hal_sensoric_
HAL Sensoric instance.
Additional Inherited Members
Protected Member Functions inherited from thread::HAWThread
void run (void *arg)
void * Arg () const
void Arg (void *a)
bool isStopped () const
void shutdownAll ()
Static Protected Member Functions inherited from thread::HAWThread
static void * entryPoint (void *)
Detailed Description
Definition at line 20 of file SensoricTest.h.
Constructor & Destructor Documentation
SensoricTest::SensoricTest ()
get HALSensoric and HALAktorik's Instances or created new ones
Definition at line 18 of file SensoricTest.cpp.
References HALAktorik::getInstance(), HALSensoric::getInstance(), hal_aktorik_, and hal_sensoric_.
SensoricTest::~SensoricTest () virtual
Free memory allocated by HALSensoric and HALAktorik's Instances and detach from channel
Definition at line 36 of file SensoricTest.cpp.
References hal_aktorik_, and hal_sensoric_.
Member Function Documentation
void SensoricTest::execute (void * arg) virtual
All tests will be implemented here ! Using macros could filter which one will be started
Implements thread::HAWThread.
Definition at line 44 of file SensoricTest.cpp.
References HALAktorik::close_Switch(), DIGITAL_CARD_CROUP0_PORTB, DIGITAL_CARD_CROUP0_PORTC, E_STOP_BUTTON, ENGINE_END, ENGINE_START, HALSensoric::getChannelId(), HALAktorik::green_Light_off(), HALAktorik::green_Light_on(), hal_aktorik_, hal_sensoric_, HEIGHT_SENSOR, HEIGHT_STATUS, thread::HAWThread::isStopped(), METAL_STATUS, HALAktorik::motor_off(), HALAktorik::motor_on(), HALAktorik::open_Switch(), RESET_BUTTON, SLIDE_STATUS, START_BUTTON, STOP_BUTTON, SWITCH_STATUS, and WP_IS_IN_SWITCH.
void SensoricTest::shutdown () virtual
this function must be implemented in the derived class. The function is called once after the thread has been stopped.
Implements thread::HAWThread.
Definition at line 226 of file SensoricTest.cpp.
Member Data Documentation
HALAktorik* SensoricTest::hal_aktorik_ private
HAL Aktorik instance.
Definition at line 29 of file SensoricTest.h.
Referenced by execute(), SensoricTest(), and ~SensoricTest().
HALSensoric* SensoricTest::hal_sensoric_ private
HAL Sensoric instance.
Definition at line 30 of file SensoricTest.h.
Referenced by execute(), SensoricTest(), and ~SensoricTest().
The documentation for this class was generated from the following files:
SensoricTest.h
SensoricTest.cpp