Festo: HALSensoric Class Reference
HALSensoric Class Reference
#include <HALSensoric.h>
Public Member Functions
virtual ~HALSensoric ()
Destructor.
int getChannelId ()
int calculateHeight ()
Static Public Member Functions
static HALSensoric * getInstance ()
Singleton pattern implementation.
Private Member Functions
HALSensoric ()
Constructor.
void initInterrupt ()
initialize interrupt's options
Private Attributes
struct sigevent event_
int channel_id_
Channel id.
int interrupt_id_
Interrupt id.
uint8_t portC_state_
Port C state.
uint8_t portB_state_
Port B state.
Static Private Attributes
static Mutex hal_Sensoric_mutex_ = Mutex()
Needed for thread-safe implemetation.
static HALSensoric * hal_Sensoric_instance_ = NULL
Singelton pattern instance for HALSensoric.
Detailed Description
Definition at line 21 of file HALSensoric.h.
Constructor & Destructor Documentation
HALSensoric::~HALSensoric () virtual
Destructor.
Free memory allocated by HALSensoric instance destroy own channel and detach interrupt
Definition at line 35 of file HALSensoric.cpp.
References channel_id_, hal_Sensoric_instance_, and interrupt_id_.
HALSensoric::HALSensoric () private
Constructor.
Call Interrupt's initializer routine
Definition at line 26 of file HALSensoric.cpp.
References initInterrupt().
Referenced by getInstance().
Member Function Documentation
int HALSensoric::calculateHeight ()
Returns
height Worksspace's height after conversion A/D
Return Workpiece's height after A/D conversion
Definition at line 156 of file HALSensoric.cpp.
References A_IOBASE, AIO_CONVERT_CONTROL, BIT_1, and BIT_7.
int HALSensoric::getChannelId ()
Returns
channel_id Channel id used in HAL Sensoric
Return channel id of Hal Sensoric. That's the only way other classes could get the channel id because as parameter it's private
Definition at line 188 of file HALSensoric.cpp.
References channel_id_.
Referenced by SensoricTest::execute(), and Demultiplexer::execute().
HALSensoric * HALSensoric::getInstance () static
Singleton pattern implementation.
Returns
HALSensoric's instance
Definition at line 44 of file HALSensoric.cpp.
References hal_Sensoric_instance_, hal_Sensoric_mutex_, HALSensoric(), Mutex::lock(), and Mutex::unlock().
Referenced by Demultiplexer::init(), and SensoricTest::SensoricTest().
void HALSensoric::initInterrupt () private
initialize interrupt's options
Initialize interrupt's options Called once in constructor
Definition at line 99 of file HALSensoric.cpp.
References channel_id_, DIGITAL_CARD_CROUP0_PORTB, DIGITAL_CARD_CROUP0_PORTC, event_, INTERRUPT_CTR_REG, interrupt_id_, INTERRUPT_STATUS_REG, IRQ, ISR(), PB_CTR, PC_LOW_CTR, portB_state_, and portC_state_.
Referenced by HALSensoric().
Member Data Documentation
int HALSensoric::channel_id_ private
Channel id.
Definition at line 44 of file HALSensoric.h.
Referenced by getChannelId(), initInterrupt(), and ~HALSensoric().
struct sigevent HALSensoric::event_ private
Definition at line 43 of file HALSensoric.h.
Referenced by initInterrupt().
HALSensoric * HALSensoric::hal_Sensoric_instance_ = NULL static private
Singelton pattern instance for HALSensoric.
Definition at line 42 of file HALSensoric.h.
Referenced by getInstance(), and ~HALSensoric().
Mutex HALSensoric::hal_Sensoric_mutex_ = Mutex() static private
Needed for thread-safe implemetation.
Definition at line 41 of file HALSensoric.h.
Referenced by getInstance().
int HALSensoric::interrupt_id_ private
Interrupt id.
Definition at line 45 of file HALSensoric.h.
Referenced by initInterrupt(), and ~HALSensoric().
uint8_t HALSensoric::portB_state_ private
Port B state.
Definition at line 47 of file HALSensoric.h.
Referenced by initInterrupt().
uint8_t HALSensoric::portC_state_ private
Port C state.
Definition at line 46 of file HALSensoric.h.
Referenced by initInterrupt().
The documentation for this class was generated from the following files:
HAL/HALSensoric.h
HAL/HALSensoric.cpp