Festo: PortC Class Reference
PortC Class Reference
#include <PortC.h>
Public Member Functions
PortC ()
Constructor.
virtual ~PortC ()
Destructor.
void Start_LED_on ()
Turn Start-LED on.
void Start_LED_off ()
Turn Start-LED off.
void Reset_LED_on ()
Turn Reset-LED on.
void Reset_LED_off ()
Turn Reset-LED off.
void Q1_LED_on ()
Turn Q1-LED on.
void Q1_LED_off ()
Turn Q1-LED off.
void Q2_LED_on ()
Turn Q2-LED on.
void Q2_LED_off ()
Turn Q2-LED off.
Private Member Functions
void set_Bit_on (uint8_t bitNumber)
Set a bit on.
void set_Bit_off (uint8_t bitNumber)
Set a bit off.
Static Private Attributes
static Mutex portC_mutex_ = Mutex()
Mutex for thread-safe implementation.
Detailed Description
Definition at line 17 of file PortC.h.
Constructor & Destructor Documentation
PortC::PortC ()
Constructor.
Constructor does nothing
Definition at line 25 of file PortC.cpp.
PortC::~PortC () virtual
Destructor.
Destructor does nothing
Definition at line 31 of file PortC.cpp.
Member Function Documentation
void PortC::Q1_LED_off ()
Turn Q1-LED off.
See Also
set_Bit_off()
Definition at line 111 of file PortC.cpp.
References BIT_2, and set_Bit_off().
void PortC::Q1_LED_on ()
Turn Q1-LED on.
See Also
set_Bit_on()
Definition at line 104 of file PortC.cpp.
References BIT_2, and set_Bit_on().
void PortC::Q2_LED_off ()
Turn Q2-LED off.
See Also
set_Bit_off()
Definition at line 125 of file PortC.cpp.
References BIT_3, and set_Bit_off().
void PortC::Q2_LED_on ()
Turn Q2-LED on.
See Also
set_Bit_on()
Definition at line 118 of file PortC.cpp.
References BIT_3, and set_Bit_on().
void PortC::Reset_LED_off ()
Turn Reset-LED off.
See Also
set_Bit_off()
Definition at line 97 of file PortC.cpp.
References BIT_1, and set_Bit_off().
void PortC::Reset_LED_on ()
Turn Reset-LED on.
See Also
set_Bit_on()
Definition at line 90 of file PortC.cpp.
References BIT_1, and set_Bit_on().
void PortC::set_Bit_off (uint8_t bitNumber) private
Set a bit off.
Parameters
bitNumber Bit's mask to set off
This method takes the bit's mask which has to be set off as parameter and it's thread-safe.
See Also
portC_mutex
Definition at line 55 of file PortC.cpp.
References DIGITAL_CARD_CROUP0_PORTC, Mutex::lock(), portC_mutex_, and Mutex::unlock().
Referenced by Q1_LED_off(), Q2_LED_off(), Reset_LED_off(), and Start_LED_off().
void PortC::set_Bit_on (uint8_t bitNumber) private
Set a bit on.
Parameters
bitNumber Bit's mask to set on
This method takes the bit's mask which has to be set on as parameter and it's thread-safe.
See Also
portC_mutex
Definition at line 38 of file PortC.cpp.
References DIGITAL_CARD_CROUP0_PORTC, Mutex::lock(), portC_mutex_, and Mutex::unlock().
Referenced by Q1_LED_on(), Q2_LED_on(), Reset_LED_on(), and Start_LED_on().
void PortC::Start_LED_off ()
Turn Start-LED off.
See Also
set_Bit_off()
Definition at line 83 of file PortC.cpp.
References BIT_0, and set_Bit_off().
void PortC::Start_LED_on ()
Turn Start-LED on.
See Also
set_Bit_on()
Definition at line 76 of file PortC.cpp.
References BIT_0, and set_Bit_on().
Member Data Documentation
Mutex PortC::portC_mutex_ = Mutex() static private
Mutex for thread-safe implementation.
Mutex locks and unlocks access to Port C to assure thread-safe implementation.
See Also
set_Bit_on()
set_Bit_off()
Definition at line 33 of file PortC.h.
Referenced by set_Bit_off(), and set_Bit_on().
The documentation for this class was generated from the following files:
HAL/PortC.h
HAL/PortC.cpp