Festo: SwitchTest Class Reference
SwitchTest Class Reference
#include <SwitchTest.h>
Public Member Functions
SwitchTest ()
virtual ~SwitchTest ()
Public Member Functions inherited from thread::HAWThread
HAWThread ()
virtual ~HAWThread ()
void start (void *arg)
void stop ()
void join () const
void hold ()
void cont ()
Private Member Functions
virtual void execute (void *arg)
virtual void shutdown ()
Additional Inherited Members
Protected Member Functions inherited from thread::HAWThread
void run (void *arg)
void * Arg () const
void Arg (void *a)
bool isStopped () const
void shutdownAll ()
Static Protected Member Functions inherited from thread::HAWThread
static void * entryPoint (void *)
Detailed Description
Definition at line 14 of file SwitchTest.h.
Constructor & Destructor Documentation
SwitchTest::SwitchTest ()
Definition at line 12 of file SwitchTest.cpp.
SwitchTest::~SwitchTest () virtual
Definition at line 17 of file SwitchTest.cpp.
Member Function Documentation
void SwitchTest::execute (void *) private virtual
   * (loop)
to be implemented in the derived class. The application programmer has to write his own loop. He can check bool isStopped() to see if the thread should exit the loop.
Implements thread::HAWThread.
Definition at line 21 of file SwitchTest.cpp.
References HALAktorik::close_Switch(), HALAktorik::getInstance(), HALAktorik::open_Switch(), WAIT_ONE_S, and WAIT_THREE_S.
void SwitchTest::shutdown () private virtual
this function must be implemented in the derived class. The function is called once after the thread has been stopped.
Implements thread::HAWThread.
Definition at line 34 of file SwitchTest.cpp.
The documentation for this class was generated from the following files:
Tests/SwitchTest.h
Tests/SwitchTest.cpp