Festo: testCplusplus.cc File Reference
testCplusplus.cc File Reference
#include "HWaccess.h"
#include <cstdlib>
#include <iostream>
#include <unistd.h>
#include <errno.h>
#include "SensoricTest.h"
#include "HALSensoric.h"
#include "Demultiplexer.h"
#include "Dispatcher.h"
Macros
#define DISPATCHER_TEST
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
#define DISPATCHER_TEST
Definition at line 24 of file testCplusplus.cc.
Function Documentation
int main (int argc, char * argv[])
Definition at line 50 of file testCplusplus.cc.
References Dispatcher::getInstance(), thread::HAWThread::join(), and thread::HAWThread::start().